
package tr.com.avea.pims_partner.schema.smsnotification;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Pims", targetNamespace = "http://www.avea.com.tr/pims-partner/schema/smsNotification")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    tr.com.avea.pims.schema_common.ObjectFactory.class,
    tr.com.avea.pims_partner.schema.smsnotification.ObjectFactory.class
})
public interface Pims {


    /**
     * 
     * @param notifySmsDeliveryReportRequest
     * @return
     *     returns tr.com.avea.pims_partner.schema.smsnotification.NotifySmsDeliveryReportResponse
     */
    @WebMethod(operationName = "NotifySmsDeliveryReport")
    @WebResult(name = "NotifySmsDeliveryReportResponse", targetNamespace = "http://www.avea.com.tr/pims-partner/schema/smsNotification", partName = "NotifySmsDeliveryReportResponse")
    public NotifySmsDeliveryReportResponse notifySmsDeliveryReport(
        @WebParam(name = "NotifySmsDeliveryReportRequest", targetNamespace = "http://www.avea.com.tr/pims-partner/schema/smsNotification", partName = "NotifySmsDeliveryReportRequest")
        NotifySmsDeliveryReportRequest notifySmsDeliveryReportRequest);

    /**
     * 
     * @param notifySmsReceptionRequest
     * @return
     *     returns tr.com.avea.pims_partner.schema.smsnotification.NotifySmsReceptionResponse
     */
    @WebMethod(operationName = "NotifySmsReception")
    @WebResult(name = "NotifySmsReceptionResponse", targetNamespace = "http://www.avea.com.tr/pims-partner/schema/smsNotification", partName = "NotifySmsReceptionResponse")
    public NotifySmsReceptionResponse notifySmsReception(
        @WebParam(name = "NotifySmsReceptionRequest", targetNamespace = "http://www.avea.com.tr/pims-partner/schema/smsNotification", partName = "NotifySmsReceptionRequest")
        NotifySmsReceptionRequest notifySmsReceptionRequest);

}
