
package com.kasim.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Pims", targetNamespace = "http://www.avea.com.tr/pims/schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Pims {


    /**
     * 
     * @param sendMmsRequest
     * @return
     *     returns com.kasim.test.SendMmsResponse
     */
    @WebMethod(operationName = "SendMms")
    @WebResult(name = "SendMmsResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "SendMmsResponse")
    public SendMmsResponse sendMms(
        @WebParam(name = "SendMmsRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "SendMmsRequest")
        SendMmsRequest sendMmsRequest);

    /**
     * 
     * @param stopSubscriptionRequest
     * @return
     *     returns com.kasim.test.StopSubscriptionResponse
     */
    @WebMethod(operationName = "StopSubscription")
    @WebResult(name = "StopSubscriptionResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "StopSubscriptionResponse")
    public StopSubscriptionResponse stopSubscription(
        @WebParam(name = "StopSubscriptionRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "StopSubscriptionRequest")
        StopSubscriptionRequest stopSubscriptionRequest);

    /**
     * 
     * @param resumeAllSubscriptionsRequest
     * @return
     *     returns com.kasim.test.ResumeAllSubscriptionsResponse
     */
    @WebMethod(operationName = "ResumeAllSubscriptions")
    @WebResult(name = "ResumeAllSubscriptionsResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "ResumeAllSubscriptionsResponse")
    public ResumeAllSubscriptionsResponse resumeAllSubscriptions(
        @WebParam(name = "ResumeAllSubscriptionsRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "ResumeAllSubscriptionsRequest")
        ResumeAllSubscriptionsRequest resumeAllSubscriptionsRequest);

    /**
     * 
     * @param resumeSubscriptionRequest
     * @return
     *     returns com.kasim.test.ResumeSubscriptionResponse
     */
    @WebMethod(operationName = "ResumeSubscription")
    @WebResult(name = "ResumeSubscriptionResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "ResumeSubscriptionResponse")
    public ResumeSubscriptionResponse resumeSubscription(
        @WebParam(name = "ResumeSubscriptionRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "ResumeSubscriptionRequest")
        ResumeSubscriptionRequest resumeSubscriptionRequest);

    /**
     * 
     * @param createSubscriptionRequest
     * @return
     *     returns com.kasim.test.CreateSubscriptionResponse
     */
    @WebMethod(operationName = "CreateSubscription")
    @WebResult(name = "CreateSubscriptionResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "CreateSubscriptionResponse")
    public CreateSubscriptionResponse createSubscription(
        @WebParam(name = "CreateSubscriptionRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "CreateSubscriptionRequest")
        CreateSubscriptionRequest createSubscriptionRequest);

    /**
     * 
     * @param querySubscriptionRequest
     * @return
     *     returns com.kasim.test.QuerySubscriptionResponse
     */
    @WebMethod(operationName = "QuerySubscription")
    @WebResult(name = "QuerySubscriptionResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "QuerySubscriptionResponse")
    public QuerySubscriptionResponse querySubscription(
        @WebParam(name = "QuerySubscriptionRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "QuerySubscriptionRequest")
        QuerySubscriptionRequest querySubscriptionRequest);

    /**
     * 
     * @param migrateSubscriptionRequest
     * @return
     *     returns com.kasim.test.MigrateSubscriptionResponse
     */
    @WebMethod(operationName = "MigrateSubscription")
    @WebResult(name = "MigrateSubscriptionResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "MigrateSubscriptionResponse")
    public MigrateSubscriptionResponse migrateSubscription(
        @WebParam(name = "MigrateSubscriptionRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "MigrateSubscriptionRequest")
        MigrateSubscriptionRequest migrateSubscriptionRequest);

    /**
     * 
     * @param dcReservePurchaseRequest
     * @return
     *     returns com.kasim.test.DCReservePurchaseResponse
     */
    @WebMethod(operationName = "DCReservePurchase")
    @WebResult(name = "DCReservePurchaseResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "DCReservePurchaseResponse")
    public DCReservePurchaseResponse dcReservePurchase(
        @WebParam(name = "DCReservePurchaseRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "DCReservePurchaseRequest")
        DCReservePurchaseRequest dcReservePurchaseRequest);

    /**
     * 
     * @param queryAllSubscriptionsRequest
     * @return
     *     returns com.kasim.test.QueryAllSubscriptionsResponse
     */
    @WebMethod(operationName = "QueryAllSubscriptions")
    @WebResult(name = "QueryAllSubscriptionsResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "QueryAllSubscriptionsResponse")
    public QueryAllSubscriptionsResponse queryAllSubscriptions(
        @WebParam(name = "QueryAllSubscriptionsRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "QueryAllSubscriptionsRequest")
        QueryAllSubscriptionsRequest queryAllSubscriptionsRequest);

    /**
     * 
     * @param dcPurchaseProductRequest
     * @return
     *     returns com.kasim.test.DCPurchaseProductResponse
     */
    @WebMethod(operationName = "DCPurchaseProduct")
    @WebResult(name = "DCPurchaseProductResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "DCPurchaseProductResponse")
    public DCPurchaseProductResponse dcPurchaseProduct(
        @WebParam(name = "DCPurchaseProductRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "DCPurchaseProductRequest")
        DCPurchaseProductRequest dcPurchaseProductRequest);

    /**
     * 
     * @param reservePurchaseRequest
     * @return
     *     returns com.kasim.test.ReservePurchaseResponse
     */
    @WebMethod(operationName = "ReservePurchase")
    @WebResult(name = "ReservePurchaseResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "ReservePurchaseResponse")
    public ReservePurchaseResponse reservePurchase(
        @WebParam(name = "ReservePurchaseRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "ReservePurchaseRequest")
        ReservePurchaseRequest reservePurchaseRequest);

    /**
     * 
     * @param dcSendWapPushRequest
     * @return
     *     returns com.kasim.test.DCSendWapPushResponse
     */
    @WebMethod(operationName = "DCSendWapPush")
    @WebResult(name = "DCSendWapPushResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "DCSendWapPushResponse")
    public DCSendWapPushResponse dcSendWapPush(
        @WebParam(name = "DCSendWapPushRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "DCSendWapPushRequest")
        DCSendWapPushRequest dcSendWapPushRequest);

    /**
     * 
     * @param sendWapPushRequest
     * @return
     *     returns com.kasim.test.SendWapPushResponse
     */
    @WebMethod(operationName = "SendWapPush")
    @WebResult(name = "SendWapPushResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "SendWapPushResponse")
    public SendWapPushResponse sendWapPush(
        @WebParam(name = "SendWapPushRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "SendWapPushRequest")
        SendWapPushRequest sendWapPushRequest);

    /**
     * 
     * @param releasePurchaseRequest
     * @return
     *     returns com.kasim.test.ReleasePurchaseResponse
     */
    @WebMethod(operationName = "ReleasePurchase")
    @WebResult(name = "ReleasePurchaseResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "ReleasePurchaseResponse")
    public ReleasePurchaseResponse releasePurchase(
        @WebParam(name = "ReleasePurchaseRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "ReleasePurchaseRequest")
        ReleasePurchaseRequest releasePurchaseRequest);

    /**
     * 
     * @param dcSendSmsRequest
     * @return
     *     returns com.kasim.test.DCSendSmsResponse
     */
    @WebMethod(operationName = "DCSendSms")
    @WebResult(name = "DCSendSmsResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "DCSendSmsResponse")
    public DCSendSmsResponse dcSendSms(
        @WebParam(name = "DCSendSmsRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "DCSendSmsRequest")
        DCSendSmsRequest dcSendSmsRequest);

    /**
     * 
     * @param sendBulkSmsRequest
     * @return
     *     returns com.kasim.test.SendBulkSmsResponse
     */
    @WebMethod(operationName = "SendBulkSms")
    @WebResult(name = "SendBulkSmsResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "SendBulkSmsResponse")
    public SendBulkSmsResponse sendBulkSms(
        @WebParam(name = "SendBulkSmsRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "SendBulkSmsRequest")
        SendBulkSmsRequest sendBulkSmsRequest);

    /**
     * 
     * @param mapIvtRequest
     * @return
     *     returns com.kasim.test.MapIvtResponse
     */
    @WebMethod(operationName = "MapIvt")
    @WebResult(name = "MapIvtResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "MapIvtResponse")
    public MapIvtResponse mapIvt(
        @WebParam(name = "MapIvtRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "MapIvtRequest")
        MapIvtRequest mapIvtRequest);

    /**
     * 
     * @param purchaseProductRequest
     * @return
     *     returns com.kasim.test.PurchaseProductResponse
     */
    @WebMethod(operationName = "PurchaseProduct")
    @WebResult(name = "PurchaseProductResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "PurchaseProductResponse")
    public PurchaseProductResponse purchaseProduct(
        @WebParam(name = "PurchaseProductRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "PurchaseProductRequest")
        PurchaseProductRequest purchaseProductRequest);

    /**
     * 
     * @param checkCreditRequest
     * @return
     *     returns com.kasim.test.CheckCreditResponse
     */
    @WebMethod(operationName = "CheckCredit")
    @WebResult(name = "CheckCreditResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "CheckCreditResponse")
    public CheckCreditResponse checkCredit(
        @WebParam(name = "CheckCreditRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "CheckCreditRequest")
        CheckCreditRequest checkCreditRequest);

    /**
     * 
     * @param sendSmsRequest
     * @return
     *     returns com.kasim.test.SendSmsResponse
     */
    @WebMethod(operationName = "SendSms")
    @WebResult(name = "SendSmsResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "SendSmsResponse")
    public SendSmsResponse sendSms(
        @WebParam(name = "SendSmsRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "SendSmsRequest")
        SendSmsRequest sendSmsRequest);

    /**
     * 
     * @param suspendAllSubscriptionsRequest
     * @return
     *     returns com.kasim.test.SuspendAllSubscriptionsResponse
     */
    @WebMethod(operationName = "SuspendAllSubscriptions")
    @WebResult(name = "SuspendAllSubscriptionsResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "SuspendAllSubscriptionsResponse")
    public SuspendAllSubscriptionsResponse suspendAllSubscriptions(
        @WebParam(name = "SuspendAllSubscriptionsRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "SuspendAllSubscriptionsRequest")
        SuspendAllSubscriptionsRequest suspendAllSubscriptionsRequest);

    /**
     * 
     * @param upgradeSubscriptionRequest
     * @return
     *     returns com.kasim.test.UpgradeSubscriptionResponse
     */
    @WebMethod(operationName = "UpgradeSubscription")
    @WebResult(name = "UpgradeSubscriptionResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "UpgradeSubscriptionResponse")
    public UpgradeSubscriptionResponse upgradeSubscription(
        @WebParam(name = "UpgradeSubscriptionRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "UpgradeSubscriptionRequest")
        UpgradeSubscriptionRequest upgradeSubscriptionRequest);

    /**
     * 
     * @param commitPurchaseRequest
     * @return
     *     returns com.kasim.test.CommitPurchaseResponse
     */
    @WebMethod(operationName = "CommitPurchase")
    @WebResult(name = "CommitPurchaseResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "CommitPurchaseResponse")
    public CommitPurchaseResponse commitPurchase(
        @WebParam(name = "CommitPurchaseRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "CommitPurchaseRequest")
        CommitPurchaseRequest commitPurchaseRequest);

    /**
     * 
     * @param stopAllSubscriptionsRequest
     * @return
     *     returns com.kasim.test.StopAllSubscriptionsResponse
     */
    @WebMethod(operationName = "StopAllSubscriptions")
    @WebResult(name = "StopAllSubscriptionsResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "StopAllSubscriptionsResponse")
    public StopAllSubscriptionsResponse stopAllSubscriptions(
        @WebParam(name = "StopAllSubscriptionsRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "StopAllSubscriptionsRequest")
        StopAllSubscriptionsRequest stopAllSubscriptionsRequest);

    /**
     * 
     * @param dcSendMmsRequest
     * @return
     *     returns com.kasim.test.DCSendMmsResponse
     */
    @WebMethod(operationName = "DCSendMms")
    @WebResult(name = "DCSendMmsResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "DCSendMmsResponse")
    public DCSendMmsResponse dcSendMms(
        @WebParam(name = "DCSendMmsRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "DCSendMmsRequest")
        DCSendMmsRequest dcSendMmsRequest);

    /**
     * 
     * @param suspendSubscriptionRequest
     * @return
     *     returns com.kasim.test.SuspendSubscriptionResponse
     */
    @WebMethod(operationName = "SuspendSubscription")
    @WebResult(name = "SuspendSubscriptionResponse", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "SuspendSubscriptionResponse")
    public SuspendSubscriptionResponse suspendSubscription(
        @WebParam(name = "SuspendSubscriptionRequest", targetNamespace = "http://www.avea.com.tr/pims/schema", partName = "SuspendSubscriptionRequest")
        SuspendSubscriptionRequest suspendSubscriptionRequest);

}
